version    =    1.000000
usage    =    "MD"
mapping    =    {
	lod_bias    =    0.000000
	anisotropy    =    0.000000
	address_u    =    "wrap"
	address_v    =    "wrap"
}
rendering    =    {
	use_akill    =    FALSE
	akill_ref    =    127
	linear_rgb    =   FALSE
	sm_hi    =    FALSE
	detail_density    =    0.000000
	detail_scale    =    1.000000
}
isUltraHiRes    =    FALSE
//err: materials    =    
